Develop
VladimirTulsky/java-filmorate pull request #35
Opened 2022-12-26 12:15 UTC by VladimirTulsky

2022-12-27 05:36 UTC, ErkinKasymaliev requested changes
привет, очень хорошая работа!
Лаконично, читается легко. Хорошо знаете стримы и запросы хорошо построены.
Оставил 1 коммент, там на 5 минут исправить. И еще, для идентификаторов лучше используйте Long, а не int. Так как записей в БД может быть очень много и int не хватит.

2022-12-27 05:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DirectorDbStorage.java
> +        Optional<Director> director = getById(id);
разве нельзя удалить просто подставив id, не вызывая объект директора? jdbcTemplate.update возвращает кол-во измененных строк, если 0, то значит ничего не удалил, так как не нашел. Используйте это, избегайте лишних запросов в бд.
Поправьте где такое еще встречается. Вроде похожее есть в reviewDBStorage и userDBStorage

2022-12-27 17:19 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
>          Optional<Review> review = getById(id);
здесь оставили получение объекта, необходимо для добавления события в ленту

2022-12-28 07:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
>          Optional<Review> review = getById(id);
ок, понял

2022-12-28 07:27 UTC, ErkinKasymaliev approved these changes
привет, хорошая работа! 
Вы хорошо разобрались во взаимодействие между слоями сервис контроллер репозиторий. Запросы к бд резкие и четкие!
Проект принят

2023-03-14 10:12 UTC, merged