Add friends likes
VladimirTulsky/java-filmorate pull request #5
Opened 2022-11-09 19:28 UTC by VladimirTulsky

на проверку, все готово

2022-11-09 21:09 UTC, db-exp requested changes

2022-11-09 21:09 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private final String name;
Лучше еще Size добавить

2022-11-09 21:09 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Лучше на String поля еще добавить Size

2022-11-09 21:09 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return user.getFriends().stream()
Можно еще через множества - 
Set<String> s1;
Set<String> s2;
s1.retainAll(s2); - в s1 теперь только то, что есть и там и там

2022-11-09 21:09 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final Map<Integer, Film> films = new HashMap<>();
"Можно лучше" - если вместо HashMap сделать ConcurrentHashMap и вместо int filmId сделать AtomicInteger - можно учесть многопоточность

2022-11-09 21:09 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private final Map<Integer, User> users = new HashMap<>();
можно  static добавить

2022-11-09 21:09 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final Map<Integer, Film> films = new HashMap<>();
можно  static добавить

2022-11-09 21:09 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmValidationTests.java
> +public class FilmValidationTests {
"Можно лучше" - можно тестировать через Spring с поднятие контекста через SpringBootTest

2022-11-09 21:27 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private final String name;
добавил

2022-11-09 21:27 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
добавил

2022-11-09 22:10 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final Map<Integer, Film> films = new HashMap<>();
мы не проходили многопоточность, т.к. не знаю логики работы данных типов, боюсь сломать логику программы. Но обязательно изучу дополнительно и попрактикуюсь в копии проекта.
static добавил

2022-11-09 22:16 UTC, VladimirTulsky commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmValidationTests.java
> +public class FilmValidationTests {
Так же не изучали еще тестирование через Spring, у нас эта тема будет в следующем модуле. Опционально изучить не успел еще.

2022-11-09 22:16 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private final Map<Integer, User> users = new HashMap<>();
добавил

2022-11-10 11:36 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return user.getFriends().stream()
Попробовал такой вариант, протестировал через Постман, все отрабатывает, но при запуске коллекции тестов по какой-то причине часть тестов падает
        Set<Integer> s1 = userStorage.getById(firstId).getFriends();
        Set<Integer> s2 = userStorage.getById(secondId).getFriends();
        s1.retainAll(s2);
        return s1.stream()
                .filter(friendId -> userStorage.getUsers().containsKey(friendId))
                .map(userStorage::getById)
                .collect(Collectors.toList());

И данный вариант все равно получился менее компактным.

2022-11-10 11:44 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return user.getFriends().stream()
возможно подскажете в чем ошибка данного стрима

2022-11-10 16:51 UTC, db-exp approved these changes

2022-11-10 17:22 UTC, merged