Add database
VladimirTulsky/java-filmorate pull request #8
Opened 2022-12-01 19:28 UTC by VladimirTulsky

2022-12-02 17:18 UTC, ErkinKasymaliev requested changes
Привет, очень хорошая работа, но надо 1 коммент в GenreService поправить, также он к MPAService относится

2022-12-02 17:18 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Optional<Film> getById(int id) {
красава что заюзали Optional

2022-12-02 17:18 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        String sql = "SELECT * FROM genre";
здесь не так, надо для жанров и mpa создать отдельный репозиторий, а в сервисах их вызывать

2022-12-02 17:18 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +@Repository
пойдет

2022-12-02 20:02 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        String sql = "SELECT * FROM genre";
поправил, вынес некоторые методы в отдельный утилитарный класс, просьба проверить тоже

2022-12-03 23:36 UTC, VladimirTulsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +
Тут у меня возникли сомнения, нужно ли выносить методы поиска жанров и рейтинга в отдельный класс

2022-12-04 07:46 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +
Лучше Dao для рейтинга и жанра все-таки отделять. А вот в FilmService уже использовать dbfilmstorage, dbmpastorage, dbgenrestorage. То есть, на слое Dao надо разделить, а на слое сервиса уже можно гибридно делать

2022-12-04 07:47 UTC, ErkinKasymaliev approved these changes
Работа принята

2022-12-04 13:43 UTC, merged